export const SHOW_REMINDER_POPUP = "OPEN_REMINDER_POPUP";
export const CLOSE_REMINDER_POPUP = "CLOSE_REMINDER_POPUP";
export const ADD_REMINDER = "ADD_REMINDER";
export const DELETE_REMINDER = "DELETE_REMINDER";